; PHP-FPM 池配置

[www]
user = www-data
group = www-data
listen = 9000
listen.owner = www-data
listen.group = www-data
listen.mode = 0660

; 进程管理器配置
pm = dynamic
pm.max_children = 50
pm.start_servers = 5
pm.min_spare_servers = 5
pm.max_spare_servers = 35
pm.max_requests = 500

; 慢日志
slowlog = /var/log/php-fpm-slow.log
request_slowlog_timeout = 10s

; 访问日志
access.log = /var/log/php-fpm-access.log

; 错误日志
php_admin_value[error_log] = /var/log/php-fpm-error.log
php_admin_flag[log_errors] = on

; 环境变量
clear_env = no
